### ISSUE TITLE
bpf2c_fuzzer crashes on a section [index 0] has an invalid sh_name

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#1200]
### Describe the bug

bpf2c_fuzzer.exe timeout-457ab418c8b7f4ee8934bbc614c7fb035702b8b1

==6008== ERROR: libFuzzer: deadly signal
    #0 0x7ffc9626ca4d  (C:\artifacts\clang_rt.asan_dbg_dynamic-x86_64.dll+0x18005ca4d)
    #1 0x7ff60699e4ef in fuzzer::PrintStackTrace(void) D:\a\_work\1\s\src\vctools\crt\asan\llvm\compiler-rt\lib\fuzzer\FuzzerUtil.cpp:210
    #2 0x7ff6069b9796 in fuzzer::Fuzzer::CrashCallback(void) D:\a\_work\1\s\src\vctools\crt\asan\llvm\compiler-rt\lib\fuzzer\FuzzerLoop.cpp:233
    #3 0x7ffcb0848e04  (C:\Windows\SYSTEM32\ucrtbased.dll+0x1800a8e04)
    #4 0x7ffcb08444f3  (C:\Windows\SYSTEM32\ucrtbased.dll+0x1800a44f3)
    #5 0x7ffcb0845442  (C:\Windows\SYSTEM32\ucrtbased.dll+0x1800a5442)
    #6 0x7ffcb0846edc  (C:\Windows\SYSTEM32\ucrtbased.dll+0x1800a6edc)
    #7 0x7ffcb084532f  (C:\Windows\SYSTEM32\ucrtbased.dll+0x1800a532f)
    #8 0x7ffcb081fc3e  (C:\Windows\SYSTEM32\ucrtbased.dll+0x18007fc3e)
    #9 0x7ffcb082a378  (C:\Windows\SYSTEM32\ucrtbased.dll+0x18008a378)
    #10 0x7ffcb082a244  (C:\Windows\SYSTEM32\ucrtbased.dll+0x18008a244)
    #11 0x7ffcb082a6d5  (C:\Windows\SYSTEM32\ucrtbased.dll+0x18008a6d5)
    #12 0x7ff606971d44 in bpf_code_generator::sanitize_name(class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>> const &) D:\a\ebpf-for-windows\ebpf-for-windows\tools\bpf2c\bpf_code_generator.cpp:1140
    #13 0x7ff60693d0ef in bpf_code_generator::emit_c_code(class std::basic_ostream<char, struct std::char_traits<char>> &) D:\a\ebpf-for-windows\ebpf-for-windows\tools\bpf2c\bpf_code_generator.cpp:1008
    #14 0x7ff606989245 in LLVMFuzzerTestOneInput D:\a\ebpf-for-windows\ebpf-for-windows\tests\libfuzzer\bpf2c\libfuzz_harness.cpp:31
    #15 0x7ff6069ba3cf in fuzzer::Fuzzer::ExecuteCallback(unsigned char const *, unsigned __int64) D:\a\_work\1\s\src\vctools\crt\asan\llvm\compiler-rt\lib\fuzzer\FuzzerLoop.cpp:559
    #16 0x7ff6069ad86d in fuzzer::RunOneTest(class fuzzer::Fuzzer *, char const *, unsigned __int64) D:\a\_work\1\s\src\vctools\crt\asan\llvm\compiler-rt\lib\fuzzer\FuzzerDriver.cpp:301
    #17 0x7ff6069a8956 in fuzzer::FuzzerDriver(int *, char ***, int (__cdecl *)(unsigned char const *, unsigned __int64)) D:\a\_work\1\s\src\vctools\crt\asan\llvm\compiler-rt\lib\fuzzer\FuzzerDriver.cpp:803
    #18 0x7ff606996342 in main D:\a\_work\1\s\src\vctools\crt\asan\llvm\compiler-rt\lib\fuzzer\FuzzerMain.cpp:20
    #19 0x7ff60698e4b8 in invoke_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    #20 0x7ff60698e40d in __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    #21 0x7ff60698e2cd in __scrt_common_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:330
    #22 0x7ff60698e52d in mainCRTStartup D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_main.cpp:16
    #23 0x7ffcca227033  (C:\Windows\System32\KERNEL32.DLL+0x180017033)
    #24 0x7ffccc022650  (C:\Windows\SYSTEM32\ntdll.dll+0x180052650)

NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal

### Steps taken to reproduce bug

bpf2c_fuzzer.exe timeout-457ab418c8b7f4ee8934bbc614c7fb035702b8b1
[timeout-457ab418c8b7f4ee8934bbc614c7fb035702b8b1.zip](https://github.com/microsoft/ebpf-for-windows/files/8882755/timeout-457ab418c8b7f4ee8934bbc614c7fb035702b8b1.zip)

### Expected behavior

Doesn't crash

### Actual outcome

Crashes

**Comment by Alan-Jowett** [comment]
C:\artifacts>llvm-objdump --all-headers timeout-457ab418c8b7f4ee8934bbc614c7fb035702b8b1

timeout-457ab418c8b7f4ee8934bbc614c7fb035702b8b1:       file format elf64-bpf
architecture: bpfel
start address: 0x0000000000000000

Program Header:

Dynamic Section:
llvm-objdump.exe: error: 'timeout-457ab418c8b7f4ee8934bbc614c7fb035702b8b1': a section [index 0] has an invalid sh_name (0x28000000) offset which goes past the end of the section name string table
