### ISSUE TITLE
verifier_fuzzer.exe crash 42e00cd42229150e43ed1aa313a7678a306b09bf

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#1203]
### Describe the bug

C:\artifacts\verifier>..\verifier_fuzzer.exe crash-42e00cd42229150e43ed1aa313a7678a306b09bf
INFO: Seed: 387285789
INFO: Loaded 1 modules   (19160 inline 8-bit counters): 19160 [00007FF6BE301000, 00007FF6BE305AD8),
..\verifier_fuzzer.exe: Running 1 inputs 1 time(s) each.
Running: crash-42e00cd42229150e43ed1aa313a7678a306b09bf
==9880== libFuzzer: run interrupted; exiting

C:\artifacts\verifier>..\verifier_fuzzer.exe crash-42e00cd42229150e43ed1aa313a7678a306b09bf
INFO: Seed: 510309477
INFO: Loaded 1 modules   (19160 inline 8-bit counters): 19160 [00007FF6BE301000, 00007FF6BE305AD8),
..\verifier_fuzzer.exe: Running 1 inputs 1 time(s) each.
Running: crash-42e00cd42229150e43ed1aa313a7678a306b09bf
==8360== ERROR: libFuzzer: deadly signal
    #0 0x7ffc9757ca4d  (C:\artifacts\clang_rt.asan_dbg_dynamic-x86_64.dll+0x18005ca4d)
    #1 0x7ff6be115caf in fuzzer::PrintStackTrace(void) D:\a\_work\1\s\src\vctools\crt\asan\llvm\compiler-rt\lib\fuzzer\FuzzerUtil.cpp:210
    #2 0x7ff6be12a596 in fuzzer::Fuzzer::CrashCallback(void) D:\a\_work\1\s\src\vctools\crt\asan\llvm\compiler-rt\lib\fuzzer\FuzzerLoop.cpp:233
    #3 0x7ffc9a078e04  (C:\Windows\SYSTEM32\ucrtbased.dll+0x1800a8e04)
    #4 0x7ffc9a073de4  (C:\Windows\SYSTEM32\ucrtbased.dll+0x1800a3de4)
    #5 0x7ffc9a0753f2  (C:\Windows\SYSTEM32\ucrtbased.dll+0x1800a53f2)
    #6 0x7ffc9a0762c8  (C:\Windows\SYSTEM32\ucrtbased.dll+0x1800a62c8)
    #7 0x7ffc9a0752af  (C:\Windows\SYSTEM32\ucrtbased.dll+0x1800a52af)
    #8 0x7ff6be249a94 in std::bitset<512>::_Validate(unsigned __int64) C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\bitset:72
    #9 0x7ff6be240a79 in std::bitset<512>::operator[](unsigned __int64) const C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\bitset:85
    #10 0x7ff6be24dec9 in bitset_domain_t::uniformity(unsigned __int64, int) const D:\a\ebpf-for-windows\ebpf-for-windows\external\ebpf-verifier\src\crab\bitset_domain.hpp:66
    #11 0x7ff6be22f805 in crab::domains::array_domain_t::load(class crab::domains::SplitDBM &, enum crab::data_kind_t, class linear_expression_t const &, int) D:\a\ebpf-for-windows\ebpf-for-windows\external\ebpf-verifier\src\crab\array_domain.cpp:501
    #12 0x7ff6be25809b in ebpf_domain_t::do_load_stack(class crab::domains::SplitDBM &, struct asm_syntax::Reg const &, class linear_expression_t const &, int, struct asm_syntax::Reg const &) D:\a\ebpf-for-windows\ebpf-for-windows\external\ebpf-verifier\src\crab\ebpf_domain.cpp:1012
    #13 0x7ff6be259914 in ebpf_domain_t::do_load(struct asm_syntax::Mem const &, struct asm_syntax::Reg const &) D:\a\ebpf-for-windows\ebpf-for-windows\external\ebpf-verifier\src\crab\ebpf_domain.cpp:1113
    #14 0x7ff6be252791 in ebpf_domain_t::operator()(struct asm_syntax::Mem const &) D:\a\ebpf-for-windows\ebpf-for-windows\external\ebpf-verifier\src\crab\ebpf_domain.cpp:1233
    #15 0x7ff6be275de4 in std::invoke<class ebpf_domain_t &, struct asm_syntax::Mem const &>(class ebpf_domain_t &, struct asm_syntax::Mem const &) C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\type_traits:1534
    #16 0x7ff6be268a64 in std::_Variant_dispatcher<struct std::integer_sequence<unsigned __int64, 8>>::_Dispatch2<void, class ebpf_domain_t &, class std::variant<struct asm_syntax::Undefined, struct asm_syntax::Bin, struct asm_syntax::Un, struct asm_syntax::LoadMapFd, struct asm_syntax::Call, struct asm_syntax::Exit, struct asm_syntax::Jmp, struct asm_syntax::Mem, struct asm_syntax::Packet, struct asm_syntax::LockAdd, struct asm_syntax::Assume, struct asm_syntax::Assert> const &, 0>(class ebpf_domain_t &, class std::variant<struct asm_syntax::Undefined, struct asm_syntax::Bin, struct asm_syntax::Un, struct asm_syntax::LoadMapFd, struct asm_syntax::Call, struct asm_syntax::Exit, struct asm_syntax::Jmp, struct asm_syntax::Mem, struct asm_syntax::Packet, struct asm_syntax::LockAdd, struct asm_syntax::Assume, struct asm_syntax::Assert> const &) C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\variant:1499
    #17 0x7ff6be26b378 in std::_Visit_strategy<2>::_Visit2<void, struct std::_Meta_list<struct std::integer_sequence<unsigned __int64, 0>, struct std::integer_sequence<unsigned __int64, 1>, struct std::integer_sequence<unsigned __int64, 2>, struct std::integer_sequence<unsigned __int64, 3>, struct std::integer_sequence<unsigned __int64, 4>, struct std::integer_sequence<unsigned __int64, 5>, struct std::integer_sequence<unsigned __int64, 6>, struct std::integer_sequence<unsigned __int64, 7>, struct std::integer_sequence<unsigned __int64, 8>, struct std::integer_sequence<unsigned __int64, 9>, struct std::integer_sequence<unsigned __int64, 10>, struct std::integer_sequence<unsigned __int64, 11>, struct std::integer_sequence<unsigned __int64, 12>>, class ebpf_domain_t &, class std::variant<struct asm_syntax::Undefined, struct asm_syntax::Bin, struct asm_syntax::Un, struct asm_syntax::LoadMapFd, struct asm_syntax::Call, struct asm_syntax::Exit, struct asm_syntax::Jmp, struct asm_syntax::Mem, struct asm_syntax::Packet, struct asm_syntax::LockAdd, struct asm_syntax::Assume, struct asm_syntax::Assert> const &>(unsigned __int64, class ebpf_domain_t &, class std::variant<struct asm_syntax::Undefined, struct asm_syntax::Bin, struct asm_syntax::Un, struct asm_syntax::LoadMapFd, struct asm_syntax::Call, struct asm_syntax::Exit, struct asm_syntax::Jmp, struct asm_syntax::Mem, struct asm_syntax::Packet, struct asm_syntax::LockAdd, struct asm_syntax::Assume, struct asm_syntax::Assert> const &) C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\variant:1614
    #18 0x7ff6be26b61b in std::_Visit_impl<13, void, struct std::_Meta_list<struct std::integer_sequence<unsigned __int64, 0>, struct std::integer_sequence<unsigned __int64, 1>, struct std::integer_sequence<unsigned __int64, 2>, struct std::integer_sequence<unsigned __int64, 3>, struct std::integer_sequence<unsigned __int64, 4>, struct std::integer_sequence<unsigned __int64, 5>, struct std::integer_sequence<unsigned __int64, 6>, struct std::integer_sequence<unsigned __int64, 7>, struct std::integer_sequence<unsigned __int64, 8>, struct std::integer_sequence<unsigned __int64, 9>, struct std::integer_sequence<unsigned __int64, 10>, struct std::integer_sequence<unsigned __int64, 11>, struct std::integer_sequence<unsigned __int64, 12>>, class ebpf_domain_t &, class std::variant<struct asm_syntax::Undefined, struct asm_syntax::Bin, struct asm_syntax::Un, struct asm_syntax::LoadMapFd, struct asm_syntax::Call, struct asm_syntax::Exit, struct asm_syntax::Jmp, struct asm_syntax::Mem, struct asm_syntax::Packet, struct asm_syntax::LockAdd, struct asm_syntax::Assume, struct asm_syntax::Assert> const &>(class ebpf_domain_t &, class std::variant<struct asm_syntax::Undefined, struct asm_syntax::Bin, struct asm_syntax::Un, struct asm_syntax::LoadMapFd, struct asm_syntax::Call, struct asm_syntax::Exit, struct asm_syntax::Jmp, struct asm_syntax::Mem, struct asm_syntax::Packet, struct asm_syntax::LockAdd, struct asm_syntax::Assume, struct asm_syntax::Assert> const &) C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\variant:1659
    #19 0x7ff6be277b3d in std::visit<class ebpf_domain_t &, class std::variant<struct asm_syntax::Undefined, struct asm_syntax::Bin, struct asm_syntax::Un, struct asm_syntax::LoadMapFd, struct asm_syntax::Call, struct asm_syntax::Exit, struct asm_syntax::Jmp, struct asm_syntax::Mem, struct asm_syntax::Packet, struct asm_syntax::LockAdd, struct asm_syntax::Assume, struct asm_syntax::Assert> const &, void>(class ebpf_domain_t &, class std::variant<struct asm_syntax::Undefined, struct asm_syntax::Bin, struct asm_syntax::Un, struct asm_syntax::LoadMapFd, struct asm_syntax::Call, struct asm_syntax::Exit, struct asm_syntax::Jmp, struct asm_syntax::Mem, struct asm_syntax::Packet, struct asm_syntax::LockAdd, struct asm_syntax::Assume, struct asm_syntax::Assert> const &) C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\variant:1677
    #20 0x7ff6be24fd19 in ebpf_domain_t::operator()(class crab::basic_block_t const &, bool) D:\a\ebpf-for-windows\ebpf-for-windows\external\ebpf-verifier\src\crab\ebpf_domain.cpp:594
    #21 0x7ff6be28d907 in crab::interleaved_fwd_fixpoint_iterator_t::transform_to_post(struct crab::label_t const &, class ebpf_domain_t) D:\a\ebpf-for-windows\ebpf-for-windows\external\ebpf-verifier\src\crab\fwd_analyzer.cpp:73
    #22 0x7ff6be281007 in crab::interleaved_fwd_fixpoint_iterator_t::operator()(struct crab::label_t const &) D:\a\ebpf-for-windows\ebpf-for-windows\external\ebpf-verifier\src\crab\fwd_analyzer.cpp:147
    #23 0x7ff6be285c14 in std::invoke<class crab::interleaved_fwd_fixpoint_iterator_t &, struct crab::label_t &>(class crab::interleaved_fwd_fixpoint_iterator_t &, struct crab::label_t &) C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\type_traits:1534
    #24 0x7ff6be283204 in std::_Variant_dispatcher<struct std::integer_sequence<unsigned __int64, 2>>::_Dispatch2<void, class crab::interleaved_fwd_fixpoint_iterator_t &, class std::variant<class std::shared_ptr<class wto_cycle_t>, struct crab::label_t> &, 0>(class crab::interleaved_fwd_fixpoint_iterator_t &, class std::variant<class std::shared_ptr<class wto_cycle_t>, struct crab::label_t> &) C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\variant:1499
    #25 0x7ff6be28494c in std::_Visit_strategy<1>::_Visit2<void, struct std::_Meta_list<struct std::integer_sequence<unsigned __int64, 0>, struct std::integer_sequence<unsigned __int64, 1>, struct std::integer_sequence<unsigned __int64, 2>>, class crab::interleaved_fwd_fixpoint_iterator_t &, class std::variant<class std::shared_ptr<class wto_cycle_t>, struct crab::label_t> &>(unsigned __int64, class crab::interleaved_fwd_fixpoint_iterator_t &, class std::variant<class std::shared_ptr<class wto_cycle_t>, struct crab::label_t> &) C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\variant:1605
    #26 0x7ff6be284a7b in std::_Visit_impl<3, void, struct std::_Meta_list<struct std::integer_sequence<unsigned __int64, 0>, struct std::integer_sequence<unsigned __int64, 1>, struct std::integer_sequence<unsigned __int64, 2>>, class crab::interleaved_fwd_fixpoint_iterator_t &, class std::variant<class std::shared_ptr<class wto_cycle_t>, struct crab::label_t> &>(class crab::interleaved_fwd_fixpoint_iterator_t &, class std::variant<class std::shared_ptr<class wto_cycle_t>, struct crab::label_t> &) C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\variant:1659
    #27 0x7ff6be285dcd in std::visit<class crab::interleaved_fwd_fixpoint_iterator_t &, class std::variant<class std::shared_ptr<class wto_cycle_t>, struct crab::label_t> &, void>(class crab::interleaved_fwd_fixpoint_iterator_t &, class std::variant<class std::shared_ptr<class wto_cycle_t>, struct crab::label_t> &) C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\variant:1677
    #28 0x7ff6be280c18 in crab::run_forward_analyzer(class crab::cfg_t &, class ebpf_domain_t const &, bool) D:\a\ebpf-for-windows\ebpf-for-windows\external\ebpf-verifier\src\crab\fwd_analyzer.cpp:130
    #29 0x7ff6be1920aa in get_ebpf_report(class std::basic_ostream<char, struct std::char_traits<char>> &, class crab::cfg_t &, struct program_info, struct ebpf_verifier_options_t const *) D:\a\ebpf-for-windows\ebpf-for-windows\external\ebpf-verifier\src\crab_verifier.cpp:158
    #30 0x7ff6be190b6a in ebpf_verify_program(class std::basic_ostream<char, struct std::char_traits<char>> &, class std::vector<class std::tuple<struct crab::label_t, class std::variant<struct asm_syntax::Undefined, struct asm_syntax::Bin, struct asm_syntax::Un, struct asm_syntax::LoadMapFd, struct asm_syntax::Call, struct asm_syntax::Exit, struct asm_syntax::Jmp, struct asm_syntax::Mem, struct asm_syntax::Packet, struct asm_syntax::LockAdd, struct asm_syntax::Assume, struct asm_syntax::Assert>, class std::optional<struct _btf_line_info>>, class std::allocator<class std::tuple<struct crab::label_t, class std::variant<struct asm_syntax::Undefined, struct asm_syntax::Bin, struct asm_syntax::Un, struct asm_syntax::LoadMapFd, struct asm_syntax::Call, struct asm_syntax::Exit, struct asm_syntax::Jmp, struct asm_syntax::Mem, struct asm_syntax::Packet, struct asm_syntax::LockAdd, struct asm_syntax::Assume, struct asm_syntax::Assert>, class std::optional<struct _btf_line_info>>>> const &, struct program_info const &, struct ebpf_verifier_options_t const *, struct ebpf_verifier_stats_t *) D:\a\ebpf-for-windows\ebpf-for-windows\external\ebpf-verifier\src\crab_verifier.cpp:230
    #31 0x7ff6bdf3b5cb in _ebpf_api_elf_verify_section_from_stream D:\a\ebpf-for-windows\ebpf-for-windows\libs\api\Verifier.cpp:504
    #32 0x7ff6bdf655f5 in ebpf_api_elf_verify_section_from_memory D:\a\ebpf-for-windows\ebpf-for-windows\libs\api\Verifier.cpp:553
    #33 0x7ff6bdefefbb in LLVMFuzzerTestOneInput D:\a\ebpf-for-windows\ebpf-for-windows\tests\libfuzzer\verifier\libfuzz_harness.cpp:16
    #34 0x7ff6be12b1cf in fuzzer::Fuzzer::ExecuteCallback(unsigned char const *, unsigned __int64) D:\a\_work\1\s\src\vctools\crt\asan\llvm\compiler-rt\lib\fuzzer\FuzzerLoop.cpp:559
    #35 0x7ff6be1035cd in fuzzer::RunOneTest(class fuzzer::Fuzzer *, char const *, unsigned __int64) D:\a\_work\1\s\src\vctools\crt\asan\llvm\compiler-rt\lib\fuzzer\FuzzerDriver.cpp:301
    #36 0x7ff6be0fe6b6 in fuzzer::FuzzerDriver(int *, char ***, int (__cdecl *)(unsigned char const *, unsigned __int64)) D:\a\_work\1\s\src\vctools\crt\asan\llvm\compiler-rt\lib\fuzzer\FuzzerDriver.cpp:803
    #37 0x7ff6be0f3cb2 in main D:\a\_work\1\s\src\vctools\crt\asan\llvm\compiler-rt\lib\fuzzer\FuzzerMain.cpp:20
    #38 0x7ff6be0ef968 in invoke_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    #39 0x7ff6be0ef8bd in __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    #40 0x7ff6be0ef77d in __scrt_common_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:330
    #41 0x7ff6be0ef9dd in mainCRTStartup D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_main.cpp:16
    #42 0x7ffcca227033  (C:\Windows\System32\KERNEL32.DLL+0x180017033)
    #43 0x7ffccc022650  (C:\Windows\SYSTEM32\ntdll.dll+0x180052650)

NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal

[crash-42e00cd42229150e43ed1aa313a7678a306b09bf.o.zip](https://github.com/microsoft/ebpf-for-windows/files/8884264/crash-42e00cd42229150e43ed1aa313a7678a306b09bf.o.zip)

### Steps taken to reproduce bug

verifier_fuzzer.exe crash-42e00cd42229150e43ed1aa313a7678a306b09bf.o

### Expected behavior

Verification fails

### Actual outcome

Verifier crashes

**Comment by Alan-Jowett** [comment]
[crash-52eee4fe4a819dcdc70ea642b463c1ee215c9b7b.o.zip](https://github.com/microsoft/ebpf-for-windows/files/8884273/crash-52eee4fe4a819dcdc70ea642b463c1ee215c9b7b.o.zip)

**Comment by Alan-Jowett** [comment]
[crash-ade20d6bf91b2c78074e013d1e0d3da0776b87b7.o.zip](https://github.com/microsoft/ebpf-for-windows/files/8884284/crash-ade20d6bf91b2c78074e013d1e0d3da0776b87b7.o.zip)

**Comment by Alan-Jowett** [comment]
[crash-b26f566e8eca6d5292d8a2e37fa0d6b412203c01.o.zip](https://github.com/microsoft/ebpf-for-windows/files/8884285/crash-b26f566e8eca6d5292d8a2e37fa0d6b412203c01.o.zip)

**Comment by Alan-Jowett** [comment]
[crash-bbae465ed8fcadaa504ca4afe06e8e169a0c9324.o.zip](https://github.com/microsoft/ebpf-for-windows/files/8884292/crash-bbae465ed8fcadaa504ca4afe06e8e169a0c9324.o.zip)

**Comment by Alan-Jowett** [comment]
Failing on:
```
164:       79 a2 f0 f9 00 00 00 00 r2 = *(u64 *)(r10 - 1552)
```

**Comment by dthaler** [comment]
Fixed by the 2nd comment in https://github.com/vbpf/ebpf-verifier/pull/367
