### ISSUE TITLE
bpf_code_generator::sanitize_name asserts if string contains char < 0.

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#1212]
### Describe the bug

[timeout-2fdd8ce7dafecca85cfe44dd4b4aaf7e77254f6f.zip](https://github.com/microsoft/ebpf-for-windows/files/8893939/timeout-2fdd8ce7dafecca85cfe44dd4b4aaf7e77254f6f.zip)

```
bpf2c_fuzzer.exe timeout-2fdd8ce7dafecca85cfe44dd4b4aaf7e77254f6f
INFO: Seed: 3007300639
INFO: Loaded 1 modules   (10864 inline 8-bit counters): 10864 [00007FF70062A000, 00007FF70062CA70),
bpf2c_fuzzer.exe: Running 1 inputs 1 time(s) each.
Running: timeout-2fdd8ce7dafecca85cfe44dd4b4aaf7e77254f6f
==8000== ERROR: libFuzzer: deadly signal
    #0 0x7ffc8882ca4d  (C:\repro\clang_rt.asan_dbg_dynamic-x86_64.dll+0x18005ca4d)
    #1 0x7ff7005e11df in fuzzer::PrintStackTrace(void) D:\a\_work\1\s\src\vctools\crt\asan\llvm\compiler-rt\lib\fuzzer\FuzzerUtil.cpp:210
    #2 0x7ff7005fc486 in fuzzer::Fuzzer::CrashCallback(void) D:\a\_work\1\s\src\vctools\crt\asan\llvm\compiler-rt\lib\fuzzer\FuzzerLoop.cpp:233
    #3 0x7ffc89cb8e04  (C:\Windows\SYSTEM32\ucrtbased.dll+0x1800a8e04)
    #4 0x7ffc89cb44f3  (C:\Windows\SYSTEM32\ucrtbased.dll+0x1800a44f3)
    #5 0x7ffc89cb5442  (C:\Windows\SYSTEM32\ucrtbased.dll+0x1800a5442)
    #6 0x7ffc89cb6edc  (C:\Windows\SYSTEM32\ucrtbased.dll+0x1800a6edc)
    #7 0x7ffc89cb532f  (C:\Windows\SYSTEM32\ucrtbased.dll+0x1800a532f)
    #8 0x7ffc89c8fc3e  (C:\Windows\SYSTEM32\ucrtbased.dll+0x18007fc3e)
    #9 0x7ffc89c9a378  (C:\Windows\SYSTEM32\ucrtbased.dll+0x18008a378)
    #10 0x7ffc89c9a244  (C:\Windows\SYSTEM32\ucrtbased.dll+0x18008a244)
    #11 0x7ffc89c9a6d5  (C:\Windows\SYSTEM32\ucrtbased.dll+0x18008a6d5)
    #12 0x7ff7005b48c4 in bpf_code_generator::sanitize_name(class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>> const &) D:\a\ebpf-for-windows\ebpf-for-windows\tools\bpf2c\bpf_code_generator.cpp:1141
    #13 0x7ff70057f93a in bpf_code_generator::emit_c_code(class std::basic_ostream<char, struct std::char_traits<char>> &) D:\a\ebpf-for-windows\ebpf-for-windows\tools\bpf2c\bpf_code_generator.cpp:1009
    #14 0x7ff7005cbf35 in LLVMFuzzerTestOneInput D:\a\ebpf-for-windows\ebpf-for-windows\tests\libfuzzer\bpf2c\libfuzz_harness.cpp:31
    #15 0x7ff7005fd0bf in fuzzer::Fuzzer::ExecuteCallback(unsigned char const *, unsigned __int64) D:\a\_work\1\s\src\vctools\crt\asan\llvm\compiler-rt\lib\fuzzer\FuzzerLoop.cpp:559
    #16 0x7ff7005f055d in fuzzer::RunOneTest(class fuzzer::Fuzzer *, char const *, unsigned __int64) D:\a\_work\1\s\src\vctools\crt\asan\llvm\compiler-rt\lib\fuzzer\FuzzerDriver.cpp:301
    #17 0x7ff7005eb646 in fuzzer::FuzzerDriver(int *, char ***, int (__cdecl *)(unsigned char const *, unsigned __int64)) D:\a\_work\1\s\src\vctools\crt\asan\llvm\compiler-rt\lib\fuzzer\FuzzerDriver.cpp:803
    #18 0x7ff7005d9032 in main D:\a\_work\1\s\src\vctools\crt\asan\llvm\compiler-rt\lib\fuzzer\FuzzerMain.cpp:20
    #19 0x7ff7005d11a8 in invoke_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    #20 0x7ff7005d10fd in __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    #21 0x7ff7005d0fbd in __scrt_common_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:330
    #22 0x7ff7005d121d in mainCRTStartup D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_main.cpp:16
    #23 0x7ffcca227033  (C:\Windows\System32\KERNEL32.DLL+0x180017033)
    #24 0x7ffccc022650  (C:\Windows\SYSTEM32\ntdll.dll+0x180052650)

NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
```

### Steps taken to reproduce bug

bpf2c_fuzzer.exe timeout-2fdd8ce7dafecca85cfe44dd4b4aaf7e77254f6f

### Expected behavior

Succeeds

### Actual outcome

Asserts when a character in the string is outside the range [0,127].

**Comment by Alan-Jowett** [comment]
Should be. I forgot to add the text to the PR to link it to this issue.
