### ISSUE TITLE
 AddressSanitizer: heap-buffer-overflow in btf_parse_line_information

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#1735]
https://github.com/microsoft/ebpf-for-windows/actions/runs/3666222777/jobs/6197891129

```
=================================================================
==5[976](https://github.com/microsoft/ebpf-for-windows/actions/runs/3666222777/jobs/6197891129#step:16:977)==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x126a01034074 at pc 0x7ff72c0cbe6a bp 0x00f6bbb6cc80 sp 0x00f6bbb6cc80
READ of size 4 at 0x126a01034074 thread T0
    #0 0x7ff72c0cbe69 in btf_parse_line_information(class std::vector<unsigned char, class std::allocator<unsigned char>> const &, class std::vector<unsigned char, class std::allocator<unsigned char>> const &, class std::function<(class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>> const &, unsigned int, class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>> const &, class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>> const &, unsigned int, unsigned int)>) (D:\a\ebpf-for-windows\ebpf-for-windows\x64\Release\verifier_fuzzer.exe+0x14021be69)
    #1 0x7ff72c041eeb in read_elf(class std::basic_istream<char, struct std::char_traits<char>> &, class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>> const &, class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>> const &, struct ebpf_verifier_options_t const *, struct ebpf_platform_t const *) (D:\a\ebpf-for-windows\ebpf-for-windows\x64\Release\verifier_fuzzer.exe+0x140191eeb)
    #2 0x7ff72bec2fc6 in _ebpf_api_elf_verify_section_from_stream D:\a\ebpf-for-windows\ebpf-for-windows\libs\api\Verifier.cpp:516
    #3 0x7ff72bec4227 in _verify_section_from_string D:\a\ebpf-for-windows\ebpf-for-windows\libs\api\Verifier.cpp:605
    #4 0x7ff72bec4631 in ebpf_api_elf_verify_section_from_memory D:\a\ebpf-for-windows\ebpf-for-windows\libs\api\Verifier.cpp:637
    #5 0x7ff72bf9c302 in LLVMFuzzerTestOneInput D:\a\ebpf-for-windows\ebpf-for-windows\tests\libfuzzer\verifier\libfuzz_harness.cpp:18
    #6 0x7ff72bff5f9f in fuzzer::Fuzzer::ExecuteCallback(unsigned char const *, unsigned __int64) D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\fuzzer\FuzzerLoop.cpp:559
    #7 0x7ff72bff80fe in fuzzer::Fuzzer::RunOne(unsigned char const *, unsigned __int64, bool, struct fuzzer::InputInfo *, bool *) D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\fuzzer\FuzzerLoop.cpp:471
    #8 0x7ff72bff6bbd in fuzzer::Fuzzer::MutateAndTestOne(void) D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\fuzzer\FuzzerLoop.cpp:702
    #9 0x7ff72bff6683 in fuzzer::Fuzzer::Loop(class std::vector<struct fuzzer::SizedFile, class fuzzer::fuzzer_allocator<struct fuzzer::SizedFile>> &) D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\fuzzer\FuzzerLoop.cpp:838
    #10 0x7ff72bfeafe9 in fuzzer::FuzzerDriver(int *, char ***, int (__cdecl *)(unsigned char const *, unsigned __int64)) D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\fuzzer\FuzzerDriver.cpp:853
    #11 0x7ff72bfdfe82 in main D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\fuzzer\FuzzerMain.cpp:20
    #12 0x7ff72bfdac7b in invoke_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    #13 0x7ff72bfdac7b in __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    #14 0x7ffc1a1a4ecf  (C:\Windows\System32\KERNEL32.DLL+0x180014ecf)
    #15 0x7ffc1a7be40a  (C:\Windows\SYSTEM32\ntdll.dll+0x18007e40a)

0x126a01034076 is located 0 bytes to the right of 54-byte region [0x126a01034040,0x126a01034076)
allocated by thread T0 here:
    #0 0x7ff72bfd407a in operator new(unsigned __int64) D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\asan\asan_win_new_scalar_thunk.cpp:41
    #1 0x7ff72bf3065e in std::allocator<unsigned char>::allocate C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.34.31933\include\xmemory:835
    #2 0x7ff72bf3065e in std::vector<unsigned char, class std::allocator<unsigned char>>::_Buy_raw(unsigned __int64) C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.34.31933\include\vector:2052
    #3 0x7ff72c02e050 in std::vector<unsigned char, class std::allocator<unsigned char>>::_Construct_n<unsigned char *, unsigned char *>(unsigned __int64, unsigned char *&&, unsigned char *&&) (D:\a\ebpf-for-windows\ebpf-for-windows\x64\Release\verifier_fuzzer.exe+0x14017e050)
    #4 0x7ff72c02bf3d in std::vector<unsigned char, class std::allocator<unsigned char>>::vector<unsigned char, class std::allocator<unsigned char>><unsigned char *, 0>(unsigned char *, unsigned char *, class std::allocator<unsigned char> const &) (D:\a\ebpf-for-windows\ebpf-for-windows\x64\Release\verifier_fuzzer.exe+0x14017bf3d)
    #5 0x7ff72c034705 in std::_Tree<class std::_Tset_traits<unsigned short, struct std::less<unsigned short>, class std::allocator<unsigned short>, 0>>::insert<0, 0>(unsigned short &&) (D:\a\ebpf-for-windows\ebpf-for-windows\x64\Release\verifier_fuzzer.exe+0x140184705)
    #6 0x7ff72c041ec2 in read_elf(class std::basic_istream<char, struct std::char_traits<char>> &, class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>> const &, class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>> const &, struct ebpf_verifier_options_t const *, struct ebpf_platform_t const *) (D:\a\ebpf-for-windows\ebpf-for-windows\x64\Release\verifier_fuzzer.exe+0x140191ec2)
    #7 0x7ff72bec2fc6 in _ebpf_api_elf_verify_section_from_stream D:\a\ebpf-for-windows\ebpf-for-windows\libs\api\Verifier.cpp:516
    #8 0x7ff72bec4227 in _verify_section_from_string D:\a\ebpf-for-windows\ebpf-for-windows\libs\api\Verifier.cpp:605
    #9 0x7ff72bec4631 in ebpf_api_elf_verify_section_from_memory D:\a\ebpf-for-windows\ebpf-for-windows\libs\api\Verifier.cpp:637
    #10 0x7ff72bf9c302 in LLVMFuzzerTestOneInput D:\a\ebpf-for-windows\ebpf-for-windows\tests\libfuzzer\verifier\libfuzz_harness.cpp:18
    #11 0x7ff72bff5f9f in fuzzer::Fuzzer::ExecuteCallback(unsigned char const *, unsigned __int64) D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\fuzzer\FuzzerLoop.cpp:559
    #12 0x7ff72bff80fe in fuzzer::Fuzzer::RunOne(unsigned char const *, unsigned __int64, bool, struct fuzzer::InputInfo *, bool *) D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\fuzzer\FuzzerLoop.cpp:471
    #13 0x7ff72bff6bbd in fuzzer::Fuzzer::MutateAndTestOne(void) D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\fuzzer\FuzzerLoop.cpp:702
    #14 0x7ff72bff6683 in fuzzer::Fuzzer::Loop(class std::vector<struct fuzzer::SizedFile, class fuzzer::fuzzer_allocator<struct fuzzer::SizedFile>> &) D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\fuzzer\FuzzerLoop.cpp:838
    #15 0x7ff72bfeafe9 in fuzzer::FuzzerDriver(int *, char ***, int (__cdecl *)(unsigned char const *, unsigned __int64)) D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\fuzzer\FuzzerDriver.cpp:853
    #16 0x7ff72bfdfe82 in main D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\fuzzer\FuzzerMain.cpp:20
    #17 0x7ff72bfdac7b in invoke_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    #18 0x7ff72bfdac7b in __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    #19 0x7ffc1a1a4ecf  (C:\Windows\System32\KERNEL32.DLL+0x180014ecf)
    #20 0x7ffc1a7be40a  (C:\Windows\SYSTEM32\ntdll.dll+0x18007e40a)

SUMMARY: AddressSanitizer: heap-buffer-overflow (D:\a\ebpf-for-windows\ebpf-for-windows\x64\Release\verifier_fuzzer.exe+0x14021be69) in btf_parse_line_information(class std::vector<unsigned char, class std::allocator<unsigned char>> const &, class std::vector<unsigned char, class std::allocator<unsigned char>> const &, class std::function<(class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>> const &, unsigned int, class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>> const &, class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>> const &, unsigned int, unsigned int)>)
Shadow bytes around the buggy address:
  0x04ab410067b0: fa fa fa fa fd fd fd fd fd fd fd fd fa fa fa fa
  0x04ab410067c0: fd fd fd fd fd fd fd fa fa fa fa fa fd fd fd fd
  0x04ab410067d0: fd fd fd fd fa fa fa fa fd fd fd fd fd fd fd fd
  0x04ab410067e0: fa fa fa fa fd fd fd fd fd fd fd fd fa fa fa fa
  0x04ab410067f0: fd fd fd fd fd fd fd fd fa fa fa fa fd fd fd fd
=>0x04ab41006800: fd fd fd fd fa fa fa fa 00 00 00 00 00 00[06]fa
  0x04ab41006810: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x04ab41006820: fa fa fa fa fa fa fa fa fa fa fa fa fd fd fd fd
  0x04ab41006830: fd fd fd fd fa fa fa fa fd fd fd fd fd fd fd fd
  0x04ab41006840: fa fa fa fa fd fd fd fd fd fd fd fd fa fa fa fa
  0x04ab41006850: fd fd fd fd fd fd fd fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==5976==ABORTING
MS: 3 ChangeASCIIInt-ChangeByte-CMP- DE: "6\x00\x00\x00\x00\x00\x00\x00"-; base unit: 8e6ec735553a53dafa51712487c621a5e42321b6
artifact_prefix='Artifacts\'; Test unit written to Artifacts\crash-b7220d69a1e24129[984](https://github.com/microsoft/ebpf-for-windows/actions/runs/3666222777/jobs/6197891129#step:16:985)c0a1d855e5cd1146f6938
```

**Comment by Alan-Jowett** [comment]
[Artifacts-verifier_fuzzer-x64-Release.zip](https://github.com/microsoft/ebpf-for-windows/files/10210915/Artifacts-verifier_fuzzer-x64-Release.zip)
Attaching the artifact that triggers the crash to preserve it.

**Comment by delaramamiri** [comment]
[Merged PR: ](https://github.com/vbpf/ebpf-verifier/pull/436)
"btf_parser.cpp" fails when the " uint32_t line_info_record_size" is trying to calculate from the start to the end. However, the line_info_record_size is not checked for at least a size of 4 bytes.
In fact bpf_line_info_t has the following information:

bpf_line_info_t
   +0x000 insn_off         : Uint4B
   +0x004 file_name_off    : Uint4B
   +0x008 line_off         : Uint4B
   +0x00c line_col         : Uint4B
This means that line_off needs to be at least 4B and this check hasn't been done before. When a smaller size of line_off is passed, the program will crash.
verifier fuzzer is crashing [in this line](https://github.com/microsoft/ebpf-for-windows/actions/runs/3666222777/jobs/6197891129#step:16:1006)


Follow up: created issue #1790 to address update of documentation.
