### ISSUE TITLE
`netebpfext_fuzzer` failure on internal CI/CD pipeline (from ASAN)

### ISSUE THREAD

**Issue by gtrevi** [microsoft/ebpf-for-windows#1992]
### Describe the bug

On the internal CI/CD pipeline on ADO, `netebpfext_fuzzer ` failed on ASAN checks.

```cmd
Starting: Run test without Code Coverage
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.212.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
Script contents: shell
.\netebpfext_fuzzer netebpfext_corpus -max_len=12 -runs=1000 -use_value_profile=1 -artifact_prefix=Artifacts\
========================== Starting Command Output ===========================
"C:\Windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\aaf8dae5-4b13-4876-9f5d-814d9275c986.cmd""
INFO: Seed: 2616667968
INFO:        4 files found in netebpfext_corpus
INFO: seed corpus: files: 4 min: 12b max: 12b total: 48b rss: 75Mb
#9	INITED ft: 9 corp: 1/12b exec/s: 0 rss: 83Mb
=================================================================
==1260==ERROR: AddressSanitizer: global-buffer-overflow on address 0x000000000082 at pc 0x7ff6a3c12268 bp 0x00dd19f4dcd0 sp 0x00dd19f4dcd8
WRITE of size 2 at 0x000000000082 thread T0
    #0 0x7ff6a3c12267 in INETADDR_SET_PORT C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\shared\mstcpip.h:1799
    #1 0x7ff6a3c05b9f in _net_ebpf_ext_process_redirect_verdict D:\a\1\s\netebpfext\net_ebpf_ext_sock_addr.c:1256
    #2 0x7ff6a3c11036 in net_ebpf_extension_sock_addr_redirect_connection_classify(struct FWPS_INCOMING_VALUES0_ const *, struct FWPS_INCOMING_METADATA_VALUES0_ const *, void *, void const *, struct FWPS_FILTER3_ const *, unsigned __int64, struct FWPS_CLASSIFY_OUT0_*) D:\a\1\s\netebpfext\net_ebpf_ext_sock_addr.c:1529
    #3 0x7ff6a3bf9ed0 in _fwp_engine::test_callout(unsigned short, struct _GUID const &, struct _GUID const &, struct FWPS_INCOMING_VALUE0_*) D:\a\1\s\netebpfext\user\fwp_um.cpp:146
    #4 0x7ff6a3bfc566 in _fwp_engine::test_cgroup_sock_addr(unsigned short, struct _GUID const &, struct _GUID const &, struct FWPS_INCOMING_VALUE0_*) D:\a\1\s\netebpfext\user\fwp_um.cpp:170
    #5 0x7ff6a3bfa563 in _fwp_engine::test_cgroup_inet4_connect(void) D:\a\1\s\netebpfext\user\fwp_um.cpp:239
    #6 0x7ff6a3b977d5 in _netebpf_ext_helper::test_cgroup_inet4_connect(void) D:\a\1\s\tests\netebpfext_unit\netebpf_ext_helper.h:62
    #7 0x7ff6a3b98483 in LLVMFuzzerTestOneInput D:\a\1\s\tests\libfuzzer\netebpfext_fuzzer\libfuzz_harness.cpp:117
    #8 0x7ff6a3c63fdf in fuzzer::Fuzzer::ExecuteCallback(unsigned char const *, unsigned __int64) D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\fuzzer\FuzzerLoop.cpp:559
    #9 0x7ff6a3c665c0 in fuzzer::Fuzzer::RunOne(unsigned char const *, unsigned __int64, bool, struct fuzzer::InputInfo *, bool *) D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\fuzzer\FuzzerLoop.cpp:471
    #10 0x7ff6a3c64f06 in fuzzer::Fuzzer::MutateAndTestOne(void) D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\fuzzer\FuzzerLoop.cpp:702
    #11 0x7ff6a3c649e7 in fuzzer::Fuzzer::Loop(class std::vector<struct fuzzer::SizedFile, class fuzzer::fuzzer_allocator<struct fuzzer::SizedFile>> &) D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\fuzzer\FuzzerLoop.cpp:838
    #12 0x7ff6a3c35a64 in fuzzer::FuzzerDriver(int *, char ***, int (__cdecl *)(unsigned char const *, unsigned __int64)) D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\fuzzer\FuzzerDriver.cpp:853
    #13 0x7ff6a3c2a4b2 in main D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\fuzzer\FuzzerMain.cpp:20
    #14 0x7ff6a3c26338 in invoke_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    #15 0x7ff6a3c2628d in __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    #16 0x7ff6a3c2614d in __scrt_common_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:330
    #17 0x7ff6a3c263ad in mainCRTStartup D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_main.cpp:16
    #18 0x7ffbb0e54ddf  (C:\Windows\System32\KERNEL32.DLL+0x180014ddf)
    #19 0x7ffbb1cfe40a  (C:\Windows\SYSTEM32\ntdll.dll+0x18007e40a)

AddressSanitizer: nested bug in the same thread, aborting.
##[error]Cmd.exe exited with code '1'.
Finishing: Run test without Code Coverage
```

**Comment by dthaler** [comment]
Github failure: https://github.com/microsoft/ebpf-for-windows/actions/runs/4105736778/jobs/7083395071
