### ISSUE TITLE
Access violation in bpf_object__open

### ISSUE THREAD

**Issue by mtfriesen** [microsoft/ebpf-for-windows#2134]
### Describe the bug

The XDP stress stress crashes with a NULL access violation in `bpf_object__open`.

### OS information

`17763.1.amd64fre.rs5_release.180914-1434`

### Steps taken to reproduce bug

Run XDP + eBPF stress test with ASAN enabled.

### Expected behavior

The process should not crash.

### Actual outcome

The process crashes.

### Additional details

Attached is the ebpfapi.dll and matching PDB to resolve proper symbols: [ebpfapi_symbols.zip](https://github.com/microsoft/ebpf-for-windows/files/10828800/ebpfapi_symbols.zip)

```
==2436==ERROR: AddressSanitizer: access-violation on unknown address 0x000000000000 (pc 0x7ffffcb98f3d bp 0x00ae0b8feb40 sp 0x00ae0b8fea40 T119)
==2436==The signal is caused by a READ memory access.
==2436==Hint: address points to the zero page.
    #0 0x7ffffcb98f3c in libbpf_num_possible_cpus+0x662c (C:\ebpf\EbpfApi.dll+0x180098f3c)
    #1 0x7ffffcb9f5e1 in libbpf_num_possible_cpus+0xccd1 (C:\ebpf\EbpfApi.dll+0x18009f5e1)
    #2 0x7ffffcb7f66b  (C:\ebpf\EbpfApi.dll+0x18007f66b)
    #3 0x7ffffcb880d5 in ebpf_object_get+0xd95 (C:\ebpf\EbpfApi.dll+0x1800880d5)
    #4 0x7ffffcba4cb6 in bpf_object__open+0x66 (C:\ebpf\EbpfApi.dll+0x1800a4cb6)
    #5 0x7ff774b328f9 in AttachXdpEbpfProgram D:\xdp\test\spinxsk\spinxsk.c:440
    #6 0x7ff774b33dab in AttachXdpProgram D:\xdp\test\spinxsk\spinxsk.c:563
    #7 0x7ff774b3b5e9 in FuzzSocketMisc D:\xdp\test\spinxsk\spinxsk.c:1451
    #8 0x7ff774b3ea68 in XskFuzzerWorkerFn D:\xdp\test\spinxsk\spinxsk.c:1885
    #9 0x7ff774b6c519 in __asan::AsanThread::ThreadStart D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\asan\asan_thread.cpp:262
    #10 0x7ff80ebc7ad3 in BaseThreadInitThunk+0x13 (C:\Windows\System32\KERNEL32.DLL+0x180017ad3)
    #11 0x7ff81137a370 in RtlUserThreadStart+0x20 (C:\Windows\SYSTEM32\ntdll.dll+0x18005a370)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: access-violation (C:\ebpf\EbpfApi.dll+0x180098f3c) in libbpf_num_possible_cpus+0x662c
Thread T119 created by T4 here:
    #0 0x7ff774b6af0f in __asan_wrap_CreateThread D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\asan\asan_win.cpp:149
    #1 0x7ff774b40b34 in QueueWorkerFn D:\xdp\test\spinxsk\spinxsk.c:2053
    #2 0x7ff774b6c519 in __asan::AsanThread::ThreadStart D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\asan\asan_thread.cpp:262
    #3 0x7ff80ebc7ad3 in BaseThreadInitThunk+0x13 (C:\Windows\System32\KERNEL32.DLL+0x180017ad3)
    #4 0x7ff81137a370 in RtlUserThreadStart+0x20 (C:\Windows\SYSTEM32\ntdll.dll+0x18005a370)

Thread T4 created by T0 here:
    #0 0x7ff774b6af0f in __asan_wrap_CreateThread D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\asan\asan_win.cpp:149
    #1 0x7ff774b440de in main D:\xdp\test\spinxsk\spinxsk.c:2411
    #2 0x7ff774b9ae38 in invoke_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    #3 0x7ff774b9ad8d in __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    #4 0x7ff774b9ac4d in __scrt_common_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:330
    #5 0x7ff774b9aead in mainCRTStartup D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_main.cpp:16
    #6 0x7ff80ebc7ad3 in BaseThreadInitThunk+0x13 (C:\Windows\System32\KERNEL32.DLL+0x180017ad3)
    #7 0x7ff81137a370 in RtlUserThreadStart+0x20 (C:\Windows\SYSTEM32\ntdll.dll+0x18005a370)

==2436==ABORTING
```

**Comment by mtfriesen** [comment]
This may be a duplicate of #2131
