### ISSUE TITLE
Add support for VS 2022

### ISSUE THREAD

**Issue by dthaler** [microsoft/ebpf-for-windows#725]
As noted in PR #724, VS 2019 Community Edition is no longer available on the Microsoft site now that VS 2022 is released.  VS 2019 is still available via other links, and other Editions of VS 2019 are still available on the Microsoft site.

We should probably support both VS 2019 and VS 2022 if we can.   This issue tracks verifying VS 2022 and updating the docs as appropriate.

**Comment by dthaler** [comment]
Trying to install WDK on a Windows 11 machine with VS 2022 installed gives:
```
1/18/2022 12:43:18 PM - Searching for applicable products...
1/18/2022 12:43:18 PM - Found installed product - Global Location
1/18/2022 12:43:18 PM - Found installed product - Visual Studio Community 2022
1/18/2022 12:43:18 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by dthaler** [comment]
Blocked on https://github.com/MicrosoftDocs/windows-driver-docs/issues/2988

**Comment by Alan-Jowett** [comment]
@dthaler looks like a preview version of the WDK is available now that supports VS 2022.
https://docs.microsoft.com/en-us/windows-hardware/drivers/installing-preview-versions-wdk

Will try it out and see if we can build using it.

**Comment by dthaler** [comment]
@gtrevi @delaramamiri can you look at this one, since you two asked about it? :)

**Comment by gtrevi** [comment]
@dthaler sure :), can you please assign it to me (don't have the privileges as of yet)?
